/*
 * Swagger YAIT
 *
 * This is the swagger of Yet Another Issue Tracker
 *
 * API version: 1.0.0
 * Contact: fabio.percivaldi@hotmail.it
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
)

func AddProject(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
