/*
 * Swagger YAIT
 *
 * This is the swagger of Yet Another Issue Tracker
 *
 * API version: 1.0.0
 * Contact: fabio.percivaldi@hotmail.it
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Sprint struct {

	Number string `json:"number,omitempty"`

	StartDate string `json:"startDate,omitempty"`

	EndDate string `json:"endDate,omitempty"`

	Completed bool `json:"completed,omitempty"`
}
