---
swagger: "2.0"
info:
  description: "This is the swagger of Yet Another Issue Tracker"
  version: "1.0.0"
  title: "Swagger YAIT"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "fabio.percivaldi@hotmail.it"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v1"
tags:
- name: "Issue"
  description: "CRUD operation for issue"
- name: "Sprint"
  description: "CRUD operation for sprint"
schemes:
- "https"
- "http"
security:
- ApiKeyAuth: []
paths:
  /sprints:
    post:
      tags:
      - "Sprint"
      summary: "Add a new sprint"
      description: ""
      operationId: "addSprint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Sprint object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Sprint"
        x-exportParamName: "Body"
      responses:
        "405":
          description: "Invalid input"
  /{sprintId}/issues:
    post:
      tags:
      - "Issue"
      summary: "Add a new issue to the sprint"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Issue"
        x-exportParamName: "Body"
      - name: "sprintId"
        in: "path"
        description: "Id of the sprint that the issue need to be added to"
        required: true
        type: "string"
        x-exportParamName: "SprintId"
      responses:
        "405":
          description: "Invalid input"
securityDefinitions:
  ApiKeyAuth:
    type: "apiKey"
    name: "X-API-KEY"
    in: "header"
definitions:
  Sprint:
    type: "object"
    properties:
      number:
        type: "string"
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
      completed:
        type: "boolean"
        default: false
    example:
      number: "number"
      endDate: "2000-01-23"
      completed: false
      startDate: "2000-01-23"
  Issue:
    type: "object"
    properties:
      type:
        type: "string"
      title:
        type: "string"
      description:
        type: "string"
    example:
      description: "description"
      type: "type"
      title: "title"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
